# Brodcasting

In [1]:
import numpy as np

In [3]:
a = np.arange(5)
print(a)
print(a.size)
print(a.shape)

[0 1 2 3 4]
5
(5,)


In [4]:
b = 2

In [5]:
np.add(a,b)

array([2, 3, 4, 5, 6])

[2,2,2,2,2]
[a0+b0,a1+b1,a2+b2...............]

In [15]:
a = np.random.randint(11,30, size = (2,2))
print(a.shape)
print(a.size)

(2, 2)
4


In [16]:
b = np.random.randint(11,30, size = (1,2))
print(b.shape)
print(b.size)

(1, 2)
2


In [14]:
np.add(a,b)

array([[50, 42],
       [44, 43]], dtype=int32)