# NumPy Array Oprations

In [2]:
import numpy as np

In [12]:
list1 = [1,2,3,4]
numpyarray = np.array(list1)

In [13]:
type(numpyarray)

numpy.ndarray

In [14]:
type(list1)

list

In [15]:
numpyarray.shape

(4,)

In [16]:
row_vector = numpyarray[:,np.newaxis]

In [17]:
row_vector.shape

(4, 1)

In [18]:
print(numpyarray)

[1 2 3 4]


In [19]:
print(row_vector)

[[1]
 [2]
 [3]
 [4]]


In [25]:
col_vector = row_vector[np.newaxis,:]

In [26]:
col_vector.shape

(1, 4, 1)

In [27]:
print(col_vector)

[[[1]
  [2]
  [3]
  [4]]]


### Reshape

In [28]:
arr = np.arange(15)

In [29]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
arr2d = arr.reshape(3,5)

In [31]:
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [32]:
arr2d.ndim

2

In [33]:
arr.ndim

1

## Arthmetic Operations on NumPy Arrray

In [3]:
arr1 = np.random.randint(1,10, size = (3,3))

In [5]:
print(arr1)

[[4 3 9]
 [4 7 3]
 [3 8 4]]


In [6]:
arr2 = np.random.randint(10,20, size = (3,3))

In [7]:
print(arr2)

[[15 12 11]
 [14 10 19]
 [12 14 10]]


In [8]:
np.add(arr1,arr2)

array([[19, 15, 20],
       [18, 17, 22],
       [15, 22, 14]], dtype=int32)

In [11]:
np.subtract(arr1,arr2)

array([[-11,  -9,  -2],
       [-10,  -3, -16],
       [ -9,  -6,  -6]], dtype=int32)

In [12]:
np.multiply(arr1,arr2)

array([[ 60,  36,  99],
       [ 56,  70,  57],
       [ 36, 112,  40]], dtype=int32)

In [15]:
np.divide(arr1,arr2)

array([[0.26666667, 0.25      , 0.81818182],
       [0.28571429, 0.7       , 0.15789474],
       [0.25      , 0.57142857, 0.4       ]])

In [16]:
np.dot(arr1,arr2)

array([[210, 204, 191],
       [194, 160, 207],
       [205, 172, 225]], dtype=int32)

##### x1*x2-5*x2+30

In [18]:
ansarray = arr1*arr2-5*arr2+30
print(ansarray)

[[15  6 74]
 [16 50 -8]
 [ 6 72 20]]
