## Slicing And Indexing

In [1]:
import numpy as np

In [3]:
array1d = np.arange(10)
print(array1d)

[0 1 2 3 4 5 6 7 8 9]


### Extract Even Numbers From one Dim array

In [4]:
even = array1d[:10:2]
print(even)

[0 2 4 6 8]


# Indexing

In [5]:
array1d[5]

np.int64(5)

In [6]:
array1d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [7]:
array1d[-1]

np.int64(9)

In [8]:
array1d[-3]

np.int64(7)

In [9]:
array1d[-9]

np.int64(1)